// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxEoJyEnJlnG_7o8vtkrntXAaPn8wKqX8',
    appId: '1:973967383392:web:05361b0e949f1b4f341c05',
    messagingSenderId: '973967383392',
    projectId: 'fypproject-7b63c',
    authDomain: 'fypproject-7b63c.firebaseapp.com',
    storageBucket: 'fypproject-7b63c.firebasestorage.app',
    measurementId: 'G-CQ4GNTL1QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHq-fzOj54tawxmBQOQY_gKBEGj782OoE',
    appId: '1:973967383392:android:c1592eb9d12a7a3a341c05',
    messagingSenderId: '973967383392',
    projectId: 'fypproject-7b63c',
    storageBucket: 'fypproject-7b63c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLrNAlBwwFVRlMbnX43I4FPleCwBn8YU',
    appId: '1:973967383392:ios:fde4a01bb77c80a4341c05',
    messagingSenderId: '973967383392',
    projectId: 'fypproject-7b63c',
    storageBucket: 'fypproject-7b63c.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPLrNAlBwwFVRlMbnX43I4FPleCwBn8YU',
    appId: '1:973967383392:ios:fde4a01bb77c80a4341c05',
    messagingSenderId: '973967383392',
    projectId: 'fypproject-7b63c',
    storageBucket: 'fypproject-7b63c.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxEoJyEnJlnG_7o8vtkrntXAaPn8wKqX8',
    appId: '1:973967383392:web:24d69edd6fb73bcf341c05',
    messagingSenderId: '973967383392',
    projectId: 'fypproject-7b63c',
    authDomain: 'fypproject-7b63c.firebaseapp.com',
    storageBucket: 'fypproject-7b63c.firebasestorage.app',
    measurementId: 'G-2NLS1N3MBK',
  );
}
